#!/bin/bash
# TODO
#	Skip empty dirs
#	indent one tab

grep -Po '(?<=href=")[^"]*' ../render/html/armMusl/index.html  > href.txt
echo ".ONESHELL:" > aMake
echo "all:" > allTask
while read href
do
	echo $href":" 
	xml_grep --html --text_only 'kbd' ../render/html/armMusl/$href > txt.txt
	
	if [ -s txt.txt ] 
	then
		echo $href":" >> aMake
		echo -e '\t' "make "$href >> allTask
		while read aLine
		do
			echo -e '\t' "$aLine" >> aMake
		done < txt.txt		
	 	
	else
	 	echo "Empty"
	fi 		
done < href.txt

cat  aMake allTask > $1/makefile
